modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-device-cloud-connector/mgw-module
name: Device Cloud-Connector
description: Connect local devices to the Cloud.
license: Apache-2.0 license
author: InfAI (CC SES)
version: v0.6.6
type: add-on
deploymentType: single
dependencies:
  github.com/SENERGY-Platform/mgw-cloud-proxy/mgw-module:
    version: "<v1.0.0"
    requiredServices:
      gateway:
        - refVar: CLOUD_API_BASE_URL
          template: "http://{ref}"
          services:
            - connector
        - refVar: CLOUD_MQTT_SERVER
          template: "mqtt://{ref}:1883"
          services:
            - connector
        - refVar: LOCAL_CM_BASE_URL
          template: "http://{ref}:8080/api"
          services:
            - connector
  github.com/SENERGY-Platform/mgw-mqtt-broker:
    version: "<v2.0.0"
    requiredServices:
      broker:
        - refVar: LOCAL_MQTT_SERVER
          template: "mqtt://{ref}:1881"
          services:
            - connector
  github.com/SENERGY-Platform/device-management-service/mgw-module:
    version: "<v1.0.0"
    requiredServices:
      manager:
        - refVar: LOCAL_DM_BASE_URL
          template: "http://{ref}"
          services:
            - connector
services:
  connector:
    name: Connector
    image: ghcr.io/senergy-platform/mgw-device-cloud-connector:0.5.5
volumes:
  event-data:
    - mountPoint: /opt/connector/event-data
      services:
        - connector
inputGroups:
  log-settings:
    name: Logging
  cloud-settings:
    name: Cloud settings
  cloud-mqtt:
    name: MQTT
    group: cloud-settings
  msg-relay:
    name: Message relay settings
  msg-relay-events:
    name: Event message relay settings
  msg-relay-events-in-memory:
    name: In-Memory
    group: msg-relay-events
  msg-relay-events-persistent:
    name: Persistent
    group: msg-relay-events
configs:
  log-level:
    value: "warning"
    options:
      - "off"
      - "error"
      - "warning"
      - "info"
      - "debug"
    targets:
      - refVar: LOGGER_LEVEL
        services:
          - connector
    userInput:
      type: text
      name: Log level
      group: log-settings
    optional: true
  mqtt-log:
    dataType: int
    value: 0
    options:
      - 0
      - 1
    targets:
      - refVar: MQTT_LOG
        services:
          - connector
    userInput:
      type: number
      name: MQTT log
      group: log-settings
    optional: true
  mqtt-debug-log:
    dataType: int
    value: 0
    options:
      - 0
      - 1
    targets:
      - refVar: MQTT_DEBUG_LOG
        services:
          - connector
    userInput:
      type: number
      name: MQTT log
      group: log-settings
    optional: true
  cloud-mqtt-pub-qos:
    dataType: int
    value: 0
    options:
      - 0
      - 1
      - 2
    targets:
      - refVar: CLOUD_PUBLISH_QOS_LEVEL
        services:
          - connector
    userInput:
      type: number
      name: Cloud MQTT publish qos level
      group: cloud-mqtt
    optional: true
  cloud-mqtt-sub-qos:
    dataType: int
    value: 2
    options:
      - 0
      - 1
      - 2
    targets:
      - refVar: CLOUD_SUBSCRIBE_QOS_LEVEL
        services:
          - connector
    userInput:
      type: number
      name: Cloud MQTT subscription qos level
      group: cloud-mqtt
    optional: true
  cloud-sync-interval:
    dataType: int
    value: 1800000000000
    targets:
      - refVar: CH_SYNC_INTERVAL
        services:
          - connector
    userInput:
      type: number
      name: Cloud sync interval
      description: "Set interval for periodic syncs in nanoseconds."
      group: cloud-settings
    optional: true
  local-device-refresh-interval:
    dataType: int
    value: 5000000000
    targets:
      - refVar: LDH_REFRESH_INTERVAL
        services:
          - connector
    userInput:
      type: number
      name: Local device discovery interval
      description: "Set interval for periodic discovery of local devices in nanoseconds."
      group: cloud-settings
    optional: true
  relay-mgs-buffer:
    dataType: int
    value: 50000
    targets:
      - refVar: RH_MESSAGE_BUFFER
        services:
          - connector
    userInput:
      type: number
      name: Receive buffer size
      description: Set buffer size for device command, processes and error message relay handlers.
      group: msg-relay
    optional: true
  relay-event-msg-buffer:
    dataType: int
    value: 100000
    targets:
      - refVar: RH_EVENT_MESSAGE_BUFFER
        services:
          - connector
    userInput:
      type: number
      name: Receive buffer size
      group: msg-relay-events
    optional: true
  relay-event-msg-handler-type:
    value: "persistent"
    options:
      - "persistent"
      - "in-memory"
    targets:
      - refVar: RH_EVENT_MESSAGE_HANDLER_TYPE
        services:
          - connector
    userInput:
      type: text
      name: Relay handler type
      group: msg-relay-events
    optional: true
  relay-event-msg-persistent-storage-size:
    value: "4GB"
    targets:
      - refVar: RH_EVENT_MESSAGE_PERSISTENT_STORAGE_SIZE
        services:
          - connector
    userInput:
      type: text
      name: Storage size
      group: msg-relay-events-persistent
    optional: true
  relay-event-msg-persistent-storage-read-limit:
    dataType: int
    value: 100
    targets:
      - refVar: RH_EVENT_MESSAGE_PERSISTENT_READ_LIMIT
        services:
          - connector
    userInput:
      type: number
      name: Read limit
      description: Specifies the number of messages that can be read from the database. Can be used to tune performance, as messages can be grouped and sent in parallel.
      group: msg-relay-events-persistent
    optional: true
  max-device-cmd-age:
    dataType: int
    value: 30000000000
    targets:
      - refVar: RH_MAX_DEVICE_CMD_AGE
        services:
          - connector
    userInput:
      type: number
      name: Maximum device command age
      description: "Set the maximum age for device commands in nanoseconds."
      group: msg-relay
    optional: true
  max-device-event-age:
    dataType: int
    value: 300000000000
    targets:
      - refVar: RH_MAX_DEVICE_EVENT_AGE
        services:
          - connector
    userInput:
      type: number
      name: Maximum device event age
      description: "Set the maximum age for device events in nanoseconds."
      group: msg-relay-events-in-memory
    optional: true